# Generated by Django 4.0.4 on 2022-05-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('is_active', models.BooleanField(default=True)),
                ('doctor_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('patient_weight', models.FloatField()),
                ('patient_height', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
