# Generated by Django 4.0.4 on 2022-05-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Street name')),
                ('number', models.PositiveIntegerField(verbose_name='House number')),
                ('city', models.CharField(max_length=100, verbose_name='City name')),
                ('state', models.CharField(max_length=100, verbose_name='State name')),
                ('country', models.CharField(max_length=100, verbose_name='Country name')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, verbose_name='Patient name')),
                ('birthdate', models.DateField(verbose_name='Patient birthdate')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='patient', to='patient.address', verbose_name='Patient address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
